name: chatting
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_database: ^9.0.6
  firebase_core: ^1.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true


  assets:
    - assets/images/



  fonts:
    - family: SansPro
      fonts:
        - asset: assets/fonts/SourceSansPro-Black.ttf
        - asset: assets/fonts/SourceSansPro-Bold.ttf
          style: normal
          weight: 500
   


    - family: Bebas
      fonts:
        - asset: assets/fonts/bebas_n.ttf